#######################################################
# resnest_v8
# mixup を入れる
#######################################################
globals:
  debug: True
  comment: test!!!!!
  seed: 42
  device: cpu
  num_epochs: 45
  mri_type: 'all'
  use_amp: True


data:
  train_df_path: input/train_labels_add_imtype.csv
  train_data_dir: input/train
  test_df_path: input/sample_submission.csv
  test_data_dir: input/test 

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

dataset:
  name: DefaultDataset
  params:
      MRItype: ['FLAIR','T1w','T1wCE','T2w']
      num_imgs: 80
      img_size: 256
      aug: True
  

loader:
  train:
    batch_size: 2
    shuffle: True
    num_workers: 0
  valid:
    batch_size: 4
    shuffle: False
    num_workers: 0
  test:
    batch_size: 4
    shuffle: False
    num_workers: 0
  

model:
  name: EffNet3D
  params:
    num_classes: 2

loss:
  name: BCEWithLogitsLoss
  params:
optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

early_stopping:
  patience: 12
  delta: 0

hydra:
  run:
    dir: ./data/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/try0
  sweep:
    dir: ./data/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: try${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s] line%(lineno)d [%(levelname)s] %(message)s'
