#######################################################
# resnest_v8
# mixup を入れる
#######################################################
globals:
  debug: False
  comment: test!!!!!
  seed: 1213
  device: cuda
  num_epochs: 45
  balanced: False
  remove_short: False
  mixup: False
  folds:
    - 0

data:
  train_df_path: input/train_labels.csv
  train_data_path: input/train
  test_df_path: ./data/external_dataset/birdcall-check/test_audio
  test_audio_path: ./data/external_dataset/birdcall-check/test.csv

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

dataset:
  name: SpectrogramDatasetWithNoise
  params:
      img_size: 224
      n_random: 5
      melspectrogram_parameters:
        n_mels: 128
        fmin: 20
        fmax: 16000
  

loader:
  train:
    batch_size: 20
    shuffle: True
    num_workers: 2
  valid:
    batch_size: 10
    shuffle: False
    num_workers: 2

model:
  name: ResNeSt
  params:
    base_model: 
    pretrained: True
    n_classes: 264

loss:
  name: BCEWithLogitsLossMod
  params:

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

hydra:
  run:
    dir: ./data/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/try0
  sweep:
    dir: ./data/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: try${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s] line%(lineno)d [%(levelname)s] %(message)s'
